### ISSUE TITLE
App crash on android

### ISSUE THREAD

**Issue by imadghanimi** [dmitry-blackwave/adyen-react-native#21]
Hello,

I have an issue, 
My app crash when i call Adyen.confirmPayment(responseData.paymentSession) 

**Log:**

06-17 11:47:38.182   976  1391 I ActivityTaskManager: START u0 {cmp=com.xxxxxx.app.prod/com.adyen.checkout.ui.internal.common.activity.CheckoutActivity (has extras)} from uid 10447
06-17 11:47:38.183   976  1391 E Parcel  : Class not found when unmarshalling: com.adyen.checkout.core.internal.PaymentReferenceImpl
06-17 11:47:38.183   976  1391 E Parcel  : java.lang.ClassNotFoundException: com.adyen.checkout.core.internal.PaymentReferenceImpl
06-17 11:47:38.183   976  1391 E Parcel  : 	at java.lang.Class.classForName(Native Method)
06-17 11:47:38.183   976  1391 E Parcel  : 	at java.lang.Class.forName(Class.java:454)
06-17 11:47:38.183   976  1391 E Parcel  : 	at android.os.Parcel.readParcelableCreator(Parcel.java:3350)
06-17 11:47:38.183   976  1391 E Parcel  : 	at android.os.Parcel.readParcelable(Parcel.java:3284)
06-17 11:47:38.183   976  1391 E Parcel  : 	at android.os.Parcel.readValue(Parcel.java:3186)
06-17 11:47:38.183   976  1391 E Parcel  : 	at android.os.Parcel.readArrayMapInternal(Parcel.java:3579)
06-17 11:47:38.183   976  1391 E Parcel  : 	at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
06-17 11:47:38.183   976  1391 E Parcel  : 	at android.os.BaseBundle.unparcel(BaseBundle.java:236)
06-17 11:47:38.183   976  1391 E Parcel  : 	at android.os.BaseBundle.getString(BaseBundle.java:1196)
06-17 11:47:38.183   976  1391 E Parcel  : 	at android.content.Intent.getStringExtra(Intent.java:8889)
06-17 11:47:38.183   976  1391 E Parcel  : 	at com.android.server.wm.ActivityStarter.executeRequest(ActivityStarter.java:1128)
06-17 11:47:38.183   976  1391 E Parcel  : 	at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:894)
06-17 11:47:38.183   976  1391 E Parcel  : 	at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1710)
06-17 11:47:38.183   976  1391 E Parcel  : 	at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1560)
06-17 11:47:38.183   976  1391 E Parcel  : 	at com.android.server.wm.ActivityTaskManagerService.startActivity(ActivityTaskManagerService.java:1512)
06-17 11:47:38.183   976  1391 E Parcel  : 	at android.app.IActivityTaskManager$Stub.onTransact(IActivityTaskManager.java:1663)
06-17 11:47:38.183   976  1391 E Parcel  : 	at android.os.Binder.execTransactInternal(Binder.java:1190)
06-17 11:47:38.183   976  1391 E Parcel  : 	at android.os.Binder.execTransact(Binder.java:1159)
06-17 11:47:38.183   976  1391 E Parcel  : Caused by: java.lang.ClassNotFoundException: com.adyen.checkout.core.internal.PaymentReferenceImpl
06-17 11:47:38.183   976  1391 E Parcel  : 	... 18 more

**ON node_modules/adyen-react-natice/android/build.gradle a have this**
dependencies {
    compile 'com.facebook.react:react-native:+'
    compile "android.arch.lifecycle:extensions:2.1.0"
    compile "android.arch.core:runtime:2.1.0"
    compile "android.arch.lifecycle:viewmodel:2.1.0"
    compile "com.adyen.checkout:ui:2.4.5"
    compile "com.adyen.checkout:core-card:2.4.5"
    compile "com.adyen.checkout:util:2.4.5"
}

@mkharibalaji

**Comment by imadghanimi** [comment]
I fixed the crash byadding this style on (your_project/android/app/src/main/res/values/styles.xml)
<style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        
</style>
